### ISSUE TITLE
(playnite) Themes not applying correctly on Chocolatey installations

### ISSUE THREAD

**Issue by youvegotwq** [Hyp5r/Chocolatey#3]
_Reported via Chocolatey's Contact Maintainers option. Email of the reporter will not be listed here for privacy reasons._

### Message

> Good afternoon!
>
>Is there something special about the way Chocolatey installs Playnite? I kept trying to install themes to no avail (drag and drop the file onto the main window) and finally uninstalled via Chocolatey and reinstalled via the official executable. Worked immediately. I've gone back and forth and confirmed that this is a problem with the version installed by Chocolatey.
>
>I'd be happy to email theme files for testing if you'd like.

**Comment by youvegotwq** [comment]
### Response from me


> Hello!
> 
> The Chocolatey variant of Playnite installs using the silent install switches provided by Inno Setup. The install script is open source and visible at https://github.com/Hyp5r/Chocolatey/blob/master/playnite/tools/chocolateyinstall.ps1.
> 
> The install that Chocolatey performs should install in your user AppData folder. 
> 
> While I can’t guarantee a solution to this problem, I don’t mind looking into this as my time permits. Feel free to send me the theme you’re having issues with and I’ll see if I can replicate the issues. You my email me the files via email at william@hyp5r.io or via Discord at Hyp5r#9059.
> 
> Thanks!

**Comment by youvegotwq** [comment]
### Response from reporter

> Good evening! Theme is attached, and others can be found here: https://playnite.link/forum/forum-8.html
> Thanks for looking into it!

**Comment by youvegotwq** [comment]
### Response from me

> Here's what I've got. Note that I'm using Playnite 7.5 installed via Chocolatey myself.
> 
> For SteamNite, I was able to drag the theme file and install it successfully. Playnite asked to reboot for it to install, I hit Yes, and it restarted and applied the theme.
> 
> I tried it with another a while back, Blupur, and I ran into an issue when installing it saying the file wasn't found.
> 
> Playnite looks like it has a log file located at %AppData%\Playnite\playnite.log. Searching for the term "Blupur", I ran across these messages:
> 
>     2020-04-11 22:55:29.8017|INFO:Installing theme extenstion C:\Users\william\AppData\Local\Temp\7zE0B9DB8F8\Blupur-Desktop-0.5.1b.pthm
>     2020-04-11 22:55:29.8180|ERROR:Failed to install theme C:\Users\william\AppData\Local\Temp\7zE0B9DB8F8\Blupur-Desktop-0.5.1b.pthmSystem.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\william\AppData\Local\Temp\7zE0B9DB8F8\Blupur-Desktop-0.5.1b.pthm'.
>        at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>        at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>        at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
>        at Playnite.ThemeManager.GetDescriptionFromPackedFile(String path) in E:\Devel\Playnite\source\Playnite\Themes.cs:line 233
>        at Playnite.ThemeManager.InstallFromPackedFile(String path) in E:\Devel\Playnite\source\Playnite\Themes.cs:line 259
>        at Playnite.Plugins.ExtensionInstaller.InstallExtensionQueue() in E:\Devel\Playnite\source\Playnite\Plugins\ExtensionInstaller.cs:line 38
> 
> 
> After moving the theme file to my Desktop, then dragging it into Playnite, it was able to install successfully with the following being logged:
> 
>     2020-04-11 22:57:32.5058|INFO:Installing theme extenstion C:\Users\william\Desktop\Blupur-Desktop-0.5.1b.pthm
>     2020-04-11 22:57:34.0962|INFO:Application started from 'C:\Users\william\AppData\Local\Playnite', with '--nolibupdate' arguments.
> 
> 
> I'd recommend looking at your log file for Playnite and searching for "SteamNite" to see if you're getting any application errors after the INFO:Installing theme message. There could be an underlying bug within Playnite (which would need to be sent to the developer) or there could be an issue elsewhere.
> 
> Hope this helps! Keep me posted and let me know if you find anything.

**Comment by youvegotwq** [comment]
Haven't heard back from the reporter in 5 days, closing this issue as stale.
